//user
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST"
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE"
export const ADD_USER = "ADD_USER"
export const ADD_CENTER_USER = "ADD_CENTER_USER"

export const DELETE_USER = "DELETE_USER"
export const FETCH_USER_BY_ID = "FETCH_USER_BY_ID"
export const UPDATE_USER="UPDATE_USER"

//categorie
export const FETCH_CATEGORIE_REQUEST = "FETCH_CATEGORIE_REQUEST"
export const FETCH_CATEGORIE_SUCCESS = "FETCH_CATEGORIE_SUCCESS"
export const FETCH_CATEGORIE_FAILURE = "FETCH_CATEGORIE_FAILURE"
export const ADD_CATEGORIE = "ADD_CATEGORIE"
export const ADD_CENTER_CATEGORIE = "ADD_CENTER_CATEGORIE"

export const DELETE_CATEGORIE = "DELETE_CATEGORIE"
export const FETCH_CATEGORIE_BY_ID = "FETCH_CATEGORIE_BY_ID"
export const UPDATE_CATEGORIE="UPDATE_CATEGORIE"
//produit

export const FETCH_PRODUIT_REQUEST = "FETCH_PRODUIT_REQUEST"
export const FETCH_PRODUIT_SUCCESS = "FETCH_PRODUIT_SUCCESS"
export const FETCH_PRODUIT_FAILURE = "FETCH_PRODUIT_FAILURE"
export const ADD_PRODUIT = "ADD_PRODUIT"
export const ADD_CENTER_PRODUIT = "ADD_CENTER_PRODUIT"

export const DELETE_PRODUIT = "DELETE_PRODUIT"
export const FETCH_PRODUIT_BY_ID = "FETCH_PRODUIT_BY_ID"
export const UPDATE_PRODUIT="UPDATE_PRODUIT"
//inscription
export const INSCRIPTION = "INSCRIPTION"

export const FETCH_CENTER_PRODUIT="FETCH_CENTER_PRODUIT"

export const LOGIN = "LOGIN"





